version: '3'
services:
        db:
                image: mariadb:10.4.5-bionic
                env_file:
                        - docker.env
                container_name: league-accounts-db
                volumes:
                        - db-volume:/var/lib/mysql
        webapp:
                build:
                        context: .
                environment:
                        LEAGUE_ACCS_PORT: 80
                        LEAGUE_ACCS_DB_ADDRESS: db:3306
                        LEAGUE_ACCS_TEMPLATE_DIR: /template/*
                        # LEAGUE_ACCS_PROD: 'true'
                        # LEAGUE_ACCS_PROD_DOMAINS: your-domain.com,www.your-domain.com
                env_file:
                        - docker.env
                container_name: league-accounts-webapp
                ports:
                        - "80:80"
                        - "443:443"
                restart: on-failure
                depends_on: 
                        - db
volumes:
        db-volume:
