version: '3'
services:
        db:
                image: mariadb:10.4.5-bionic
                env_file:
                        - docker.env
                container_name: league-accounts-db
        webapp:
                build:
                        context: .
                environment:
                        LEAGUE_ACCS_PORT: 80
                        LEAGUE_ACCS_DB_ADDRESS: db:3306
                        LEAGUE_ACCS_TEMPLATE_DIR: /template/*
                env_file:
                        - docker.env
                container_name: league-accounts-webapp
                ports:
                        - "80:80"
                restart: on-failure
                depends_on: 
                        - db
