version: '3'
services:
        webapp:
                build:
                        context: .
                environment:
                        LAM_PORT: 80
                        LAM_DB_PATH: /mnt/lam.db
                        LAM_TEMPLATE_GLOB: /template/*
                        # LAM_PROD: 'true'
                        # LAM_PROD_DOMAINS: your-domain.com,www.your-domain.com
                container_name: lam
                ports:
                        - "80:80"
                        - "443:443"
                restart: on-failure
                volumes:
                        - db:/mnt
volumes:
        db:
