version: '3'
services:
        webapp:
                build:
                        context: .
                environment:
                        LAM_ADDRESS: ':80'
                        LAM_HTTPS_ADDRESS: ':443'
                        LAM_DOMAIN: 'https://your-domain.com:443'
                        LAM_CERT: '/var/lam/keypairs/server.crt'
                        LAM_KEY: '/var/lam/keypairs/server.key'
                        LAM_USERS: 'user1:bcrypt1'
                        LAM_ACCOUNTS: '/mnt/accounts.csv'
                container_name: lam
                ports:
                        - "80:80"
                        - "443:443"
                restart: on-failure
                volumes:
                        - db:/mnt
                        - path/to/keypairs:/var/lam/keypairs
volumes:
        db:
