export LEAGUE_ACCS_USER1='u1'
export LEAGUE_ACCS_USER2='u2'
export LEAGUE_ACCS_USER1_PW='p1'
export LEAGUE_ACCS_USER2_PW='p2'
export LEAGUE_ACCS_CSRF='8t93j4f943jnfun3o4fwj0239ijBZUHF'
export LEAGUE_ACCS_TEMPLATE_DIR="${HOME}/dev/league-accs/template/*"
export LEAGUE_ACCS_JSON="${HOME}/dev/league-accs/lol-accs-final.json"
echo "$LEAGUE_ACCS_USER1 $LEAGUE_ACCS_USER2 $LEAGUE_ACCS_USER1_PW $LEAGUE_ACCS_USER2_PW $LEAGUE_ACCS_CSRF $LEAGUE_ACCS_TEMPLATE_DIR $LEAGUE_ACCS_JSON"
go run main.go
